######################## default configuration ####################
baseURL = "/"
title = "DannyJRasch - Personal Blog Template"
theme = "bookworm"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "UA-118560225-1" # example : UA-123-45
# disqus short name
disqusShortname = "raschadvisory-com" # get your shortname form here : https://disqus.com

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.88.0"

############################# Image Processing ##############################
[imaging]
quality = "100"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true


############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Mulish"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#1371d6" #"#01AD9F"

#################### default parameters ################################
[params]
logo = "images/logo.svg"
logo_width = "240px"
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "DannyJRa"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "Designed By [DannyJRa](https://raschadvisory.com/) & Developed in Switzerland"

# Preloader
[params.preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Instagram feed
[params.instafeed]
enable = false
instagram_user = "bookworm"
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

#TODO: # Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours
title = "Subscribe for my monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################
[[menu.main]]
name = "Home"
url = "/"
weight = 1
  
#[[menu.main]]
#name = "About"
#url = "about/"
#weight = 3
  
[[menu.main]]
name = "Contact"
url = "https://www.raschadvisory.com/contact/"
weight = 4
  
[[menu.main]]
weight = 6
url = "#"
name = "Pages"
hasChildren = true

  #[[menu.main]]
  #parent = "Pages"
  #name = "Author"
  #url = "author/"
  #weight = 1
  
  [[menu.main]]
  parent = "Pages"
  name = "Tags"
  url = "tags/"
  weight = 2
  
  [[menu.main]]
  parent = "Pages"
  name = "Category"
  url = "categories/"
  weight = 3
  


  
  [[menu.main]]
  parent = "Pages"
  name = "Terms & Conditions"
  url = "terms-conditions/"
  weight = 6


